### ISSUE TITLE
Enabling multisampling returns error when it shouldn't.

### ISSUE THREAD

**Issue by TyOverby** [rust-windowing/glutin#575]
Only recently, when I use `with_multisampling` in my glutin/glium project I get the error `Couldn\'t find any pixel format that matches the criterias.'

This never used to happen before, and in fact, multisampling is supported (and worked) on the computer that I'm testing on!

**Comment by tomaka** [comment]
On which platform?

**Comment by TyOverby** [comment]
Linux

**Comment by paulrouget** [comment]
Could it be because of #569 ?

**Comment by tomaka** [comment]
Chances are that #569 in fact fixes it.
I just published version 0.3.5, which includes #569.

**Comment by TyOverby** [comment]
I'll check and then report back

**Comment by TyOverby** [comment]
I updated to glutin `0.3.5` and glium `0.8.5` and the error is still returned.

**Comment by tomaka** [comment]
What does `glxinfo` say?

**Comment by TyOverby** [comment]
Glxinfo dump: http://pastebin.com/raw.php?i=kizztzDX

**Comment by TyOverby** [comment]
Does anything look suspicious?

**Comment by tomaka** [comment]
Oh I forgot about this issue.

The problem is that all your pixelformats will multisampling enabled are "non-conformant" (the `Ncon` in the last column means that).
Glutin automatically filters them out: https://github.com/tomaka/glutin/blob/b8b1b80631e1335a7ab747f34e1c67dfa0790a10/src/api/glx/mod.rs#L387-L390

I don't know what the best solution to this problem is. Should this be "won't fix" or shoud glutin accept non-conformant formats?

**Comment by TyOverby** [comment]
So the implementation is non-conformant but it just happens to work anyways?  

Would it be possible to ask Glutin to "force" non-compat formats?  Like I said in the issue, multi-sampling worked fine before you checked for conformance.

I don't know how other devs do it, but I get multisampling on all the games that I play on this computer somehow.

**Comment by TyOverby** [comment]
@tomaka Could you reopen this issue?  I'm still getting the same error as before.

**Comment by dbarnhart** [comment]
I'm also getting this issue.
[glxinfo.dump.txt](https://github.com/tomaka/glutin/files/102869/glxinfo.dump.txt)

**Comment by c0gent** [comment]
Just started getting this same error as of v0.14.
glxinfo: http://pastebin.com/gYPW90gm

Perhaps a window builder setting to force/allow non-conformant modes?

**Comment by TyOverby** [comment]
I'm still getting this error.

**Comment by c0gent** [comment]
Working again now.

**Comment by jrmiller82** [comment]
Still getting this issue.

**Comment by rightfold** [comment]
I can still reproduce this.

**Comment by C-Bouthoorn** [comment]
Not 100% sure it is related, but this might be fixed with the `18.*` version of Mesa. (See https://github.com/PistonDevelopers/piston/issues/1202 for more information.)

**Comment by ZeGentzy** [comment]
Can you guys still reproduce this, or has it been fixed?

**Comment by ZeGentzy** [comment]
Assuming fixed. Reopen if not the case.
